require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false
